### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/2023-canssi-ecr-workshop#5]
**gh-pages** --> create a new branch to make these changes. use `git checkout -b ＜new-branch＞`

- [x] - edit the code within each episode to remove the lines that apply to different Nodes
- [x] - edit episode 00 code to remove any packages we will not be discussing
- [x] - remove entire lessons we're not teaching and re-number the episodes accordingly
- [x] - edit index.md to include an accurate summary of the workshop
- [x] - edit config.yml to have accurate title
- [x] - edit README.md
- [x] - remove excess files from Resources folder
- [x] - edit setup.md, including link to git repo (two places to change this) and remove extra packages we dont need
- [x] - edit Resources/install_instructions.docx, including link to git repo (two places to change this) and remove extra packages we dont need

**master** --> create a new branch to make these changes. use `git checkout -b ＜new-branch＞`
- [x] - remove excess Data folders
- [x] - remove excess Code folders
- [x] - edit README.md
- [x] - edit setup/setup.R, including link to git repo (two places to change this) and remove extra packages we dont need
- [x] - edit setup/install_instructions.docx, including link to git repo (two places to change this) and remove extra packages we dont need

**Comment by CaitlinBate** [comment]
@jackVanish this can be our running "status" of things, if we can check stuff off when we get to it :) I took this checklist from the wiki of otn-workshop-base

**Comment by CaitlinBate** [comment]
leaving assigned to Bruce to finish out

#16 will do most of this

**Comment by jackVanish** [comment]
We will have to leave this open until we have the last of Rob's code, unfortunately.

**Comment by jackVanish** [comment]
Gonna leave this open till we have the all-clear from Rob but i think we're good.
